spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: my-group-id
  datasource:
    url:
      jdbc:
        postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
